import { OMEGA_Manifest } from '../types/manifest';
import { ValidationService, ValidationIssue } from './validationService';
import { OmegaContract } from './wasmLoader';

export interface AuditResult {
  isCompliant: boolean;
  score: number; // 0-100
  status: 'DRAFT' | 'CERTIFIED' | 'CRITICAL_FAIL';
  checks: {
    governance: boolean;
    technical: boolean;
    aesthetic: boolean;
    integrity: boolean;
  };
  details: string[];
  issues: ValidationIssue[];
  fingerprint?: string; 
  isHashMatched?: boolean;
}

export class AuditService {
  static performFullAudit(manifest: OMEGA_Manifest, contract: OmegaContract | null = null): AuditResult {
    const issues = ValidationService.validate(manifest, contract);
    const details: string[] = [];
    
    let governance = true;
    let technical = true;
    let aesthetic = true;
    let integrity = true;

    // 1. CHEQUEO DE GOBERNANZA Y REGLAS DE ORO
    const criticalIssues = issues.filter(i => i.severity === 'error');
    if (criticalIssues.length > 0) {
      governance = false;
      details.push(`CRITICAL: ${criticalIssues.length} fallos críticos de gobernanza detectados.`);
    }

    // 2. CHEQUEO DE INTEGRIDAD ESPACIAL
    const integrityIssues = issues.filter(i => i.keyword === 'era7_integrity');
    if (integrityIssues.length > 0) {
      integrity = false;
      details.push(`INTEGRITY: ${integrityIssues.length} violaciones de límites físicos.`);
    }

    // 3. CHEQUEO DE AUDITORÍA PRO-MASTER
    const auditIssues = issues.filter(i => i.severity === 'audit');
    if (auditIssues.length > 0) {
      aesthetic = false;
      details.push(`PRO-MASTER: ${auditIssues.length} detalles de refinamiento pendientes.`);
    }

    // 4. CHEQUEO TÉCNICO GENERAL
    const techIssues = issues.filter(i => i.severity === 'warning');
    if (techIssues.length > 0) {
      technical = false;
      details.push(`TECHNICAL: ${techIssues.length} advertencias de configuración.`);
    }

    // CALCULO FINAL DE SCORE
    const isCompliant = issues.every(i => i.severity !== 'error');
    let score = 100;
    
    score -= issues.filter(i => i.severity === 'error').length * 15;
    score -= issues.filter(i => i.severity === 'warning').length * 5;
    score -= issues.filter(i => i.severity === 'audit').length * 2;
    
    score = Math.max(0, score);

    let status: AuditResult['status'] = 'CERTIFIED';
    if (!isCompliant) status = 'CRITICAL_FAIL';
    else if (score < 90) status = 'DRAFT';

    return {
      isCompliant,
      score,
      status,
      checks: { 
        governance, 
        technical, 
        aesthetic: aesthetic && auditIssues.length === 0, 
        integrity 
      },
      details,
      issues
    };
  }

  static generateCertificationReport(manifest: OMEGA_Manifest, audit: AuditResult): string {
    const date = new Date().toISOString().split('T')[0];
    const time = new Date().toTimeString().split(' ')[0];

    return `# OMEGA ERA 7.2.3 - CERTIFICATE OF CONFORMITY

## [ REPORT SUMMARY ]
- **Module ID**: ${manifest.id}
- **Commercial Name**: ${manifest.metadata?.name || 'Unknown'}
- **Engine Version**: ${manifest.schemaVersion || '7.2.3'}
- **Audit Timestamp**: ${date} ${time}
- **Certification Status**: ${audit.status}
- **Industrial Score**: ${audit.score}/100

## [ ARCHITECTURAL AUDIT ]
- **Governance (Golden Rules)**: ${audit.checks.governance ? 'PASSED ✅' : 'CRITICAL ❌'}
- **Structural Integrity**: ${audit.checks.integrity ? 'PASSED ✅' : 'VIOLATION ❌'}
- **Technical Standards**: ${audit.checks.technical ? 'PASSED ✅' : 'WARNING ⚠️'}
- **Pro-Master Refinement**: ${audit.checks.aesthetic ? 'CERTIFIED ✨' : 'PENDING 🛠️'}

## [ DETAILED INSPECTION LOG ]
${audit.issues.map(i => `> [${i.severity.toUpperCase()}] ${i.message}`).join('\n') || '> No critical issues detected.'}

---
*Generated by OMEGA Compliance Engine v7.2.3 — Aseptic Industrial Standard*
`;
  }
}
