import { OMEGA_Manifest } from '../types/manifest';
import { ValidationService, ValidationIssue } from './validationService';

export interface AuditResult {
  isCompliant: boolean;
  score: number; // 0-100
  status: 'DRAFT' | 'CERTIFIED' | 'CRITICAL_FAIL';
  checks: {
    governance: boolean;
    technical: boolean;
    aesthetic: boolean;
  };
  details: string[];
}

export class AuditService {
  static performFullAudit(manifest: OMEGA_Manifest): AuditResult {
    const issues = ValidationService.validate(manifest);
    const details: string[] = [];
    
    let governance = true;
    let technical = true;
    let aesthetic = true;

    // 1. CHEQUEO DE GOBERNANZA (BLOQUEANTE)
    const criticalIssues = issues.filter(i => i.keyword === 'era7_governance' || i.message.includes('ERROR'));
    if (criticalIssues.length > 0) {
      governance = false;
      details.push(`CRITICAL: ${criticalIssues.length} violaciones de gobernanza detectadas.`);
    }

    // 2. CHEQUEO TÉCNICO (BINDINGS Y RACKS)
    const allElements = [
      ...(manifest.ui?.controls || []),
      ...(manifest.ui?.jacks || [])
    ];

    if (allElements.length === 0) {
      technical = false;
      details.push('ADVERTENCIA: El módulo no contiene elementos interactivos.');
    }

    const hp = manifest.metadata?.rack?.hp || 0;
    if (hp < 2 || hp > 128) {
      technical = false;
      details.push('ERROR: Dimensiones de Rack (HP) fuera de rango estándar (2-128 HP).');
    }

    // 3. CHEQUEO ESTÉTICO (IDENTIDAD VISUAL)
    if (!manifest.ui?.skin) {
      aesthetic = false;
      details.push('MEJORA: No se ha definido una Skin industrial (usando default).');
    }

    const hasLabels = allElements.some(el => 
      el.presentation?.attachments?.some((att: any) => att.type === 'label')
    );
    if (!hasLabels) {
      aesthetic = false;
      details.push('ADVERTENCIA: No se detectan etiquetas (labels) en los componentes.');
    }

    // CALCULO FINAL
    const isCompliant = governance && technical && issues.length === 0;
    let score = 100;
    if (!isCompliant) score -= 40;
    if (!aesthetic) score -= 10;
    score = Math.max(0, score - (issues.length * 5));

    let status: AuditResult['status'] = 'CERTIFIED';
    if (!governance) status = 'CRITICAL_FAIL';
    else if (!isCompliant || score < 80) status = 'DRAFT';

    return {
      isCompliant,
      score,
      status,
      checks: { governance, technical, aesthetic },
      details
    };
  }

  static generateCertificationReport(manifest: OMEGA_Manifest, audit: AuditResult): string {
    const date = new Date().toISOString().split('T')[0];
    const time = new Date().toTimeString().split(' ')[0];

    return `# OMEGA ERA 7.1 - CERTIFICATE OF CONFORMITY

## [ REPORT SUMMARY ]
- **Module ID**: ${manifest.id}
- **Commercial Name**: ${manifest.metadata?.name || 'Unknown'}
- **Engine Version**: ${manifest.schemaVersion || '7.1'}
- **Audit Timestamp**: ${date} ${time}
- **Certification Status**: ${audit.status}
- **Industrial Score**: ${audit.score}/100

## [ GOVERNANCE STATUS ]
- **ERA 4 Compliance**: ${audit.checks.governance ? 'PASSED ✅' : 'FAILED ❌'}
- **Mandatory Roles**: ${audit.checks.governance ? 'Verified' : 'Incomplete'}

## [ TECHNICAL AUDIT ]
- **Rack Integrity**: ${audit.checks.technical ? 'Standard Compliant' : 'Warning'}
- **Component Density**: ${(manifest.ui?.controls?.length || 0) + (manifest.ui?.jacks?.length || 0)} Interactive Elements

## [ DETAILED AUDIT LOG ]
${audit.details.map(d => `> ${d}`).join('\n') || '> No critical issues detected during the engineering sweep.'}

---
*Generated by OMEGA Compliance Engine v7.1 — Aseptic Industrial Standard*
`;
  }
}
