'use client';

import React from 'react';
import { HardDrive, Palette } from 'lucide-react';

interface PortPropertiesProps {
  item: any;
  onUpdate: (updates: any) => void;
}

export default function PortProperties({ item, onUpdate }: PortPropertiesProps) {
  const pres = item.presentation || {};
  const currentVariant = pres.variant || 'plastic';

  const updateVariant = (v: string) => {
    onUpdate({ presentation: { ...pres, variant: v } });
  };

  const materials = [
    { id: 'plastic', label: 'ABS Plastic', desc: 'Standard industrial jack' },
    { id: 'metal', label: 'Chrome Steel', desc: 'Premium heavy-duty' },
    { id: 'gold', label: 'Gold Plated', desc: 'Audiophile grade' },
  ];

  return (
    <div className="space-y-6 pt-2">
      <div className="space-y-3">
        <label className="text-[8px] text-foreground/60 uppercase font-black tracking-widest flex items-center gap-2">
          <HardDrive className="w-3 h-3 text-primary" />
          <span>Socket Mechanical Material</span>
        </label>
        <div className="space-y-2">
          {materials.map((m) => (
            <button
              key={m.id}
              onClick={() => updateVariant(m.id)}
              className={`w-full p-3 border rounded-xs transition-all flex flex-col items-start gap-1 group relative overflow-hidden ${
                currentVariant === m.id 
                  ? 'bg-primary/10 border-primary shadow-[0_0_15px_rgba(0,240,255,0.1)]' 
                  : 'bg-black/40 border-outline/10 hover:border-outline/30'
              }`}
            >
              <div className="flex items-center justify-between w-full">
                <span className={`text-[9px] font-black uppercase tracking-widest ${currentVariant === m.id ? 'text-primary' : 'text-foreground/60'}`}>
                  {m.label}
                </span>
                <span className="text-[8px] font-mono opacity-20 group-hover:opacity-100 transition-opacity">.{m.id}</span>
              </div>
              <p className="text-[7px] text-foreground/30 italic uppercase">{m.desc}</p>
              {currentVariant === m.id && <div className="absolute left-0 top-0 bottom-0 w-1 bg-primary" />}
            </button>
          ))}
        </div>
      </div>

      <div className="p-4 bg-primary/5 border border-primary/10 rounded-xs space-y-2">
         <div className="flex items-center gap-2 text-[7px] font-black text-primary/40 uppercase tracking-widest">
            <Palette className="w-3 h-3" />
            <span>Signal Indication</span>
         </div>
         <p className="text-[8px] text-foreground/40 leading-relaxed italic">
            Port identification rings are automatically generated by the theme based on the <b>Signal Role</b> defined in Engineering.
         </p>
      </div>
    </div>
  );
}
